upgrade version of amplify
aws-amplify/learn pull request #449
Opened 2024-06-25 16:10 UTC by katiegoines

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-25 16:51 UTC, 404ghosting commented on .gitignore
> +credentials.csv
Place in alphabetical order please

2024-06-25 16:51 UTC, 404ghosting commented on .gitignore
> +amplify/mock-api-resources
Same feed back as above

2024-06-25 16:54 UTC, 404ghosting requested changes
Blocking since there is no staging link

2024-06-25 20:06 UTC, 404ghosting commented on .gitignore
> +credentials.csv
@reesscot what do you think?

2024-06-25 20:43 UTC, 404ghosting reviewed
Please add description of your changes?

2024-06-27 23:25 UTC, jacoblogan commented
Not sure if this staging site is up to date https://amplify-upgrade.dm6i4p3zktlna.amplifyapp.com/ but it looks like we might be losing some styling or theming with the upgrade
![Screenshot 2024-06-27 at 4 21 32 PM](https://github.com/aws-amplify/learn/assets/7351516/e4f6cad6-7492-4f7d-84b3-b54a20e1ab4a)

2024-06-28 19:21 UTC, 404ghosting commented
No courses found!!

2024-07-24 22:06 UTC, jacoblogan approved these changes

2024-07-25 04:59 UTC, timngyn commented on src/lib/getData.ts
> +  }
I'm a little confused by this loop, why do we have it? It looks like it's just accessing the properties from `contributorCourses` and just making a new object array to filter? Is there a reason we need to `await` the properties too?

2024-07-25 04:59 UTC, timngyn commented on src/models/index.d.ts
Was this updated by Amplify? Would you happen to know why it has the `Eager` and `Lazy` word in front of the type names?

2024-09-05 17:24 UTC, closed without merging